version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    container_name: app
    restart: always
    volumes:
      - ".:/usr/src"
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: root
      SPRING_RABBITMQ_PASSWORD: root
      SPRING_RABBITMQ_LISTENER_PENDING_BLOCK_QUEUE: pending-block-queue
      SPRING_RABBITMQ_LISTENER_MINED_BLOCK_QUEUE: mined-block-queue
    depends_on:
      - db
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
volumes:
  db-data:
  rabbitmq_data:
